#!/bin/zsh

old_path=$PWD

cd src/main/rust/

#cargo build
# build_path="target/debug/Course-Descritpion-Automation"
cargo build --release
build_path="target/release/Course-Description-Automation"
pwd
echo ""
echo "built copying to cda_master"
cp -f "$build_path" "$HOME/Documents/.noah/cda/"
cp -f "$build_path" "$HOME/Documents/.noah/course-description-automation/Course-Description-Automation.app"

cd $old_path
