#!/bin/bash

old_path=$PWD

cd src/main/rust/ || exit

#cargo build
# build_path="target/debug/Course-Descritpion-Automation"
cargo build --release
build_path="target/release/Course-Description-Automation"
pwd
echo ""
echo "built copying to cda_master"
cp -f "$build_path" "$HOME/Documents/.noah/cda/"
cp -f "$build_path" "$HOME/Course-Description-Automation.app/Contents/Resources/"
cp -f "$build_path" "$HOME/Course-Description-Automation2.app/Contents/Resources/"

echo "copied to $HOME/Documents/.noah/cda/ and to"
echo "$HOME/Course-Description-Automation.app/Contents/Resources/"
echo "$HOME/Course-Description-Automation2.app/Contents/Resources/"

cd "$old_path" || exit
