#!/bin/zsh
mkdir MyIcon.iconset
FILE="$1"
sips -z 32 32     "${FILE}32x32.png" --out MyIcon.iconset/icon_16x16@2x.png
sips -z 32 32     "${FILE}32x32.png" --out MyIcon.iconset/icon_32x32.png
sips -z 64 64     "${FILE}64x64.png" --out MyIcon.iconset/icon_32x32@2x.png
sips -z 256 256   "${FILE}256x256.png" --out MyIcon.iconset/icon_128x128@2x.png
sips -z 256 256   "${FILE}256x256.png" --out MyIcon.iconset/icon_256x256.png
sips -z 512 512   "${FILE}256x256@2x.png" --out MyIcon.iconset/icon_256x256@2x.png
#cp "$FILE" MyIcon.iconset/icon_512x512@2x.png
iconutil -c icns MyIcon.iconset
rm -R MyIcon.iconset
