[package]
name = "rust-para-convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.18"
log4rs = "1.2.0"
native-dialog = "0.6.3"
path-clean = "1.0.1"
rayon = "1.7.0"
