[package]
name = "par_convert_md_to_pdf"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
log = "0.4.17"
log4rs = "1.2.0"
once_cell = "1.17.1"
path-clean = "1.0.1"
rayon = "1.7.0"
winsafe = { version = "0.0.14", features = ["kernel", "shell", "user", "ole", "oleaut"] }

[[bin]]
name = "rust_para_convert-mdToPdf"
path = "src/main.rs"
test = false
bench = false
