[package]
name = "safe_execvp_win"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-clean = "1.0.1"
rayon = "1.7.0"
winsafe = {version = "0.0.14", features = ["kernel", "shell", "user", "ole", "oleaut"] }
