[package]
name = "par_convert_md_to_pdf"
version = "0.1.0"
edition = "2021"


[dependencies]
log = "0.4.17"
log4rs = "1.2.0"
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
path-clean = "1.0.1"
rayon = "1.7.0"
winsafe = { version = "0.0.15", features = ["kernel", "shell", "user", "ole", "oleaut"] }

# native-windows-gui = {path = "../../", features=["no-styling", "embed-resource", "list-view", "cursor"]}
# native-windows-derive = {path = "../../../native-windows-derive"}

[build-dependencies]
embed-resource = "1.3"

[[bin]]
name = "rust_para_convert-mdToPdf"
path = "src/main.rs"
test = false
bench = false

[[bin]]
name = "win_popup"
path = "src/win_popup/main.rs"
test = false
bench = false
