appenders:
  file_logger:
    kind: rolling_file
    # path: "../log/rust-convert.log"
    path: "files/res/log/rust-convert.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 5mb
      roller:
        kind: delete
  my_stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)} - {l}: {m}{n})}"
root:
  level: info
  appenders:
    - file_logger
